# Site settings
title: "#tech"
email: "https://instagram.com/miaulei"
description: > # this means to ignore newlines until "baseurl:"
  a channel on tech things
baseurl:  # the subpath of your site, e.g. /blog/
url:  mot-clic.tech #the base hostname & protocol for your site
twitter_username:
github_username:  lei-lo

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "/blog/page:num/"
